#!/bin/bash
menu=`compgen -c | dmenu "$@" -p "$USER@$HOSTNAME:$PWD"`
case $menu in
        *\!) echo "$menu" | cut -d'!' -f1 | ${SHELL:-"/bin/sh"} &;;
	*) $menu 2>&1 | dmenu "$@" -p "$USER@$HOSTNAME:$PWD" -l 50;;
esac
