#!/bin/bash
virt=$(virsh list --all |dmenu -l 10)
machine=$(echo $virt|awk '{print $2}');
state=$(echo $virt|awk '{print $3}');
if [[ "$state" = "shut" ]]; then
    virsh start $machine;
    virt-viewer $machine;
elif [[ "$state" = "running" ]]; then
    virt-viewer $machine;
fi
